import path from "node:path";
import { writeJsonArtifact, writeTextArtifact } from "./artifacts.js";
import { checkAllLiveAdapterOperatorEvidence } from "./liveAdapterOperatorEvidenceCheckAll.js";
import { generateLiveAdapterCutoverAudit } from "./liveAdapterCutoverAudit.js";
import { generateLiveAdapterOperatorEvidenceAudit } from "./liveAdapterOperatorEvidence.js";
import { selectNextOperatorEvidenceTarget } from "./liveAdapterOperatorEvidenceNextTarget.js";
import { generateLiveAdapterOperatorEvidenceAssist } from "./liveAdapterOperatorEvidenceAssist.js";
import { generateLiveAdapterOperatorEvidenceQueue } from "./liveAdapterOperatorEvidenceQueue.js";
import { generateLiveAdapterOperatorEvidenceWorkplan } from "./liveAdapterOperatorEvidenceWorkplan.js";
import { generateLiveAdapterOperatorEvidenceWorkspace } from "./liveAdapterOperatorEvidenceWorkspace.js";
import { type LiveAdapterTarget } from "./liveAdapterTargets.js";
import { generateLiveAdapterReviewSession } from "./liveAdapterReviewSession.js";
import { slugifyProject } from "./paths.js";
import type { LiveAdapterOperatorEvidenceNextPacket } from "./types.js";

export async function generateLiveAdapterOperatorEvidenceNextPacket(input: {
  project: string;
  vaultRoot: string;
  target?: LiveAdapterTarget;
}): Promise<{ jsonPath: string; markdownPath: string; packet: LiveAdapterOperatorEvidenceNextPacket }> {
  const project = slugifyProject(input.project);
  const workplan = await generateLiveAdapterOperatorEvidenceWorkplan({ project, vaultRoot: input.vaultRoot });
  const queue = await generateLiveAdapterOperatorEvidenceQueue({ project, vaultRoot: input.vaultRoot });
  const audit = await generateLiveAdapterOperatorEvidenceAudit({ project, vaultRoot: input.vaultRoot });
  const explicitQueueTarget = input.target
    ? queue.queue.targets.find((target) => target.target === input.target)
    : undefined;
  const selected = input.target
    ? {
        target: input.target,
        status: explicitQueueTarget?.status ?? "unchecked",
        missingSections: explicitQueueTarget?.missingSections.length ?? 0,
        nextAction: explicitQueueTarget?.nextAction
      }
    : selectNextOperatorEvidenceTarget(queue.queue, workplan.workplan, audit.audit);
  if (!selected) throw new Error("No live-adapter operator evidence target needs action.");

  const workspace = await generateLiveAdapterOperatorEvidenceWorkspace({
    project,
    vaultRoot: input.vaultRoot,
    target: selected.target
  });
  const assist = await generateLiveAdapterOperatorEvidenceAssist({
    project,
    vaultRoot: input.vaultRoot,
    target: selected.target
  });
  const checkBatch = await checkAllLiveAdapterOperatorEvidence({
    project,
    vaultRoot: input.vaultRoot,
    target: selected.target,
    source: "workspace",
    notes: "Generated by live-adapter-operator-evidence-next."
  });
  const reviewSession = await generateLiveAdapterReviewSession({
    project,
    vaultRoot: input.vaultRoot,
    target: selected.target
  });
  const cutoverAudit = await generateLiveAdapterCutoverAudit({
    project,
    vaultRoot: input.vaultRoot,
    target: selected.target
  });

  const workspaceTarget = required(
    workspace.workspace.targets.find((target) => target.target === selected.target),
    `Missing generated workspace target for ${selected.target}.`
  );
  const assistTarget = required(
    assist.assist.targets.find((target) => target.target === selected.target),
    `Missing generated assist target for ${selected.target}.`
  );
  const checkTarget = required(
    checkBatch.batch.targets.find((target) => target.target === selected.target),
    `Missing generated check target for ${selected.target}.`
  );
  const cutoverTarget = required(
    cutoverAudit.audit.targets.find((target) => target.target === selected.target),
    `Missing generated cutover target for ${selected.target}.`
  );

  const status: LiveAdapterOperatorEvidenceNextPacket["status"] =
    checkTarget.status === "complete"
      ? "ready_for_import"
      : workspaceTarget.status === "complete"
        ? "complete"
        : "operator_action_required";
  const packet: LiveAdapterOperatorEvidenceNextPacket = {
    schemaVersion: 1,
    project,
    generatedAt: new Date().toISOString(),
    target: selected.target,
    selectedBy: input.target ? "explicit" : "queue",
    status,
    mutationApproved: false,
    approvalGranted: false,
    operatorEvidenceRecordCreated: false,
    summary: {
      missingSections: checkTarget.missingSections,
      existingEvidenceRefs: assistTarget.existingEvidenceRefs.length,
      promotedLiveEvidence: assistTarget.promotedLiveEvidence.length,
      supportFileRefs: assistTarget.supportFileRefs.length,
      cutoverBlockedGates: cutoverTarget.gates.filter((gate) => gate.status === "blocked").length
    },
    refs: {
      workplan: relativeRef(input.vaultRoot, workplan.jsonPath),
      queue: relativeRef(input.vaultRoot, queue.jsonPath),
      operatorEvidenceAudit: relativeRef(input.vaultRoot, audit.jsonPath),
      workspace: relativeRef(input.vaultRoot, workspace.jsonPath),
      assist: relativeRef(input.vaultRoot, assist.jsonPath),
      checkBatch: relativeRef(input.vaultRoot, checkBatch.jsonPath),
      reviewSession: relativeRef(input.vaultRoot, reviewSession.jsonPath),
      cutoverAudit: relativeRef(input.vaultRoot, cutoverAudit.jsonPath)
    },
    commands: {
      check: workspaceTarget.checkCommand,
      import: workspaceTarget.importCommand,
      reviewSession: `npm run ariadne -- live-adapter-review-session --project ${project} --target ${selected.target}`,
      cutoverAudit: `npm run ariadne -- live-adapter-cutover-audit --project ${project} --target ${selected.target}`
    },
    nextAction: selected.nextAction,
    missingSectionLabels: checkTarget.missingSectionLabels,
    evidenceRefs: Array.from(
      new Set([
        workspaceTarget.evidenceFileRef,
        assistTarget.assistFileRef,
        ...assistTarget.existingEvidenceRefs,
        ...assistTarget.promotedLiveEvidence.map((item) => item.ref),
        ...assistTarget.supportFileRefs,
        ...cutoverTarget.evidenceRefs
      ])
    )
  };

  const fileStem = `live-adapter-operator-evidence-next-${selected.target}`;
  const jsonPath = await writeJsonArtifact(input.vaultRoot, project, "control", `${fileStem}.json`, packet);
  const markdownPath = await writeTextArtifact(input.vaultRoot, project, "control", `${fileStem}.md`, renderPacket(packet));
  return { jsonPath, markdownPath, packet };
}

function renderPacket(packet: LiveAdapterOperatorEvidenceNextPacket): string {
  return [
    `# Live Adapter Operator Evidence Next Packet: ${packet.target}`,
    "",
    `Project: ${packet.project}`,
    `Generated: ${packet.generatedAt}`,
    `Target: ${packet.target}`,
    `Selected by: ${packet.selectedBy}`,
    `Status: ${packet.status}`,
    `Mutation approved: ${packet.mutationApproved}`,
    `Approval granted: ${packet.approvalGranted}`,
    `Operator evidence record created: ${packet.operatorEvidenceRecordCreated}`,
    "",
    "## Rule",
    "",
    "This packet runs only non-mutating preparation steps. It does not import operator evidence, approve mutation, or grant live-adapter authority.",
    "",
    "## Summary",
    "",
    `- Missing sections: ${packet.summary.missingSections}`,
    `- Existing evidence refs: ${packet.summary.existingEvidenceRefs}`,
    `- Promoted live evidence: ${packet.summary.promotedLiveEvidence}`,
    `- Support file refs: ${packet.summary.supportFileRefs}`,
    `- Cutover blocked gates: ${packet.summary.cutoverBlockedGates}`,
    "",
    "## Generated Refs",
    "",
    ...Object.entries(packet.refs).map(([name, ref]) => `- ${name}: ${ref}`),
    "",
    "## Operator Commands",
    "",
    "```bash",
    packet.commands.check,
    packet.commands.import,
    packet.commands.reviewSession,
    packet.commands.cutoverAudit,
    "```",
    "",
    "## Next Action",
    "",
    `- ${packet.nextAction ?? "Fill the operator evidence workspace and rerun the check command."}`,
    "",
    "## Missing Section Labels",
    "",
    ...list(packet.missingSectionLabels),
    "",
    "## Evidence Refs",
    "",
    ...list(packet.evidenceRefs),
    ""
  ].join("\n");
}

function relativeRef(vaultRoot: string, absolutePath: string): string {
  return path.relative(vaultRoot, absolutePath).split(path.sep).join("/");
}

function required<T>(value: T | undefined, message: string): T {
  if (value === undefined) throw new Error(message);
  return value;
}

function list(items: string[]): string[] {
  return items.length === 0 ? ["- none"] : items.map((item) => `- ${item}`);
}
